---
title: "p8105_mtp_wm2473"
output: github_document
date: "2022-10-21"
---
# Importing the library
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(patchwork)
library(ggridges)
```
#Counting words
```{r}
wordcountaddin::text_stats("p8105_mtp_wm2473.Rmd")
```

#Problem 1
```{r}
# The raw data contain weights of three types of dogs. My goal is make the data more reasonable and readable for analysis by tidy and to clean the weight data and making some plots to see the realtionship of the weights and dog types. 

dog =   read_excel("./data/dogweights_07may2022.xlsx") %>% 
 janitor::clean_names() %>%  
  setNames(c("Date", "Raisin","Simone","Gagne","std", "notes")) %>% 
    filter(Date != "DATE") %>% 
  select(-notes) %>% 
  pivot_longer(Raisin: Gagne, names_to = "type", values_to = "weight") %>%
  separate(weight, into = c("lbs", "oz"), sep = " ") %>%
  mutate(Date= as.Date('1899-12-30') + days(Date), weights_lbs = as.numeric(lbs) + as.numeric(oz)/16) %>% 
  na.omit()
dog
# After import data, I found that the columns name represents the dog types is messy. So I rename all the columns according to their original names. And I found that the weight column containing two units. I separate them into "lbs" and "oz", then combining them into the weights_lbs as total weight. The date column is the number from excel and I convert them into date based on the windows stating date. Finally I dropped NA value from the data set and remove the note column for the next question.  
```

# notes dataframe(second)
```{r}
notes_df = 
  read_excel("./data/dogweights_07may2022.xlsx") %>% 
   janitor::clean_names() %>%  
  setNames(c("Date", "Raisin","Simone","Gagne","std", "notes")) %>% 
    filter(Date != "DATE") %>%
  mutate(Date= as.Date('1899-12-30') + days(Date)) %>% 
  select(Date, notes) %>% 
  drop_na(notes)
notes_df
```

#Export both dataframes as CSVs; store in the same dog directory as the raw data
```{r}
write.csv(dog,"./data/dog_weights_df.csv")
write.csv(notes_df,"./data/notes_df.csv")
```


# Problem 2
```{r}
ncol(dog)
names(dog)
nrow(dog)
# The resulting tidy weights dataset contains 6 variables the name of them are "Date", "std", "type", "lbs", "oz", "weight_lbs" and conatins 126 observations. 
```

# Summary table: containing average and standard deviation of weights
```{r}
dog %>%
  group_by(type) %>%
  summarize(num_obs = n(),
            avg_weight = mean(weights_lbs, na.rm = TRUE),
            std_weight = sd(weights_lbs, na.rm = TRUE),
           .groups = 'drop') %>%
    knitr::kable(digits = 2)
```

# Problem 3
```{r}
# weights distribution of each dog
weightsplot = 
  dog %>%
  arrange(weights_lbs, type) %>% 
  ggplot(aes(x = type, y = weights_lbs, color = type)) +
  geom_boxplot() +
  labs(
    title = "Distribution plot",
    x = "Dog Types",
    y = "Weight(lbs)"
  )+ scale_y_continuous(breaks = c(8,10,12,14,16,18,20))+ scale_color_hue(name = "Name")

weightsplot
```

# dog's weight vs time
```{r}
wt = 
  dog %>%
  arrange(weights_lbs, Date) %>% 
  ggplot(aes(x = Date, y = weights_lbs, color = type)) + geom_point(alpha = .5,scale =5)+ labs(
    title = "Weight vs Time",
    x = "Date",
    y = "Weight(lbs)"
  ) +scale_x_continuous()+  scale_x_date(
    date_breaks = "5 months",
    date_labels = "%y-%m")+
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 0))
wt
```

```{r}
weightsplot+wt
# The left "weightsplot" I use the box plot to show the distribution. We can see the Raisin has the heaviest weights compared to Gagne and Simone. And Gagne and Simone has a similar dog weights. The right "wt" shows the dog's weight over time. The weight of Gagne didn't change too much and keep stable of most of the time. Gagne has a stable weight at the beggining but after Nov 2018, its weight dropped consistenly. And there is no record from Sep 2019, from the notes we can know gagne die in 09/08/2019.Both Raisin and Simone has a weight declined over the three years period. Raisin keep decreasing weight then has a slightly increase but in 12/2020, its weight reach a minimum point. After it, slightly increase again. And Simone is the lightest dog and has a similar trend of Raisin. The weight stabilized at the beginning but start decrease around 07/2020. 03/2021 has a slightly increase then drop to the lowest point at 04/2022. 
```

```{r}
ggsave("./results/weightsplot.pdf", weightsplot, width = 8, height = 5)
ggsave("./results/weightvstime.pdf", wt, width = 8, height = 5)
ggsave("./results/two_panel_plot.pdf", weightsplot+wt, width = 8, height = 5)
```

